name: Build Python for Android

on:
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Tag or branch to build Python from'
        required: true
        default: 'v3.13.0'

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_NDK_HOME: ${{ github.workspace }}/android-ndk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-ndk:$PATH

    steps:
      - name: Install tar
        run: sudo apt-get update && sudo apt-get install -y tar unzip
      
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.build_tag }}

      - name: Set Up Android SDK
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-21"

      - name: Set Up Android NDK
        run: |
          curl -sSL https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -o android-ndk.zip
          unzip android-ndk.zip -d ${{ runner.temp }}
          mv ${{ runner.temp }}/android-ndk-r25b $ANDROID_NDK_HOME

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev zlib1g-dev

      - name: Build for armeabi-v7a
        run: |
          cd Android
          ./android.py build armeabi-v7a

      - name: Build for x86_64
        run: |
          cd Android
          ./android.py build x86_64

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cpython-android-build
          path: |
            cross-build/armeabi-v7a
            cross-build/x86_64
