name: Build Python for Android

on:
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Tag or branch to build Python from'
        required: true
        default: 'v3.13.0'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.build_tag }}

      # Step 2: Cache Android NDK
      - name: Cache Android NDK
        uses: actions/cache@v3
        with:
          path: android-ndk
          key: ndk-r25b

      - name: Download Android NDK if Not Cached
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -o android-ndk.zip
          unzip android-ndk.zip -d .
          mv android-ndk-r25b android-ndk

      # Step 3: Cache Dependencies
      - name: Cache Build Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cmake
            /usr/include
            /usr/lib
          key: build-deps-${{ runner.os }}-${{ inputs.build_tag }}

      # Step 4: Install Dependencies if Not Cached
      - name: Install Build Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake zip

      # Step 5: Build for armeabi-v7a
      - name: Configure Build for armeabi-v7a
        run: |
          export ANDROID_NDK_HOME=$PWD/android-ndk
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          cd Android
          ./configure.sh --api-level=21 --target-abi=armeabi-v7a

      - name: Build Python for armeabi-v7a
        run: |
          export ANDROID_NDK_HOME=$PWD/android-ndk
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          cd Android
          make -j$(nproc)

      # Step 6: Build for x86_64
      - name: Configure Build for x86_64
        run: |
          export ANDROID_NDK_HOME=$PWD/android-ndk
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          cd Android
          ./configure.sh --api-level=21 --target-abi=x86_64

      - name: Build Python for x86_64
        run: |
          export ANDROID_NDK_HOME=$PWD/android-ndk
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          cd Android
          make -j$(nproc)

      # Step 7: Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-android-build
          path: |
            Android/build/lib.android-21-armeabi-v7a/libpython3.13m.so
            Android/build/lib.android-21-armeabi-v7a/python
            Android/build/lib.android-21-x86_64/libpython3.13m.so
            Android/build/lib.android-21-x86_64/python
